### ISSUE TITLE
Lab 05: LIHTC model

### ISSUE THREAD

**Issue by tim-ness** [Watts-College/cpp-528-fall-2021#42]
Hi @castower 

I'm running into errors when trying to make the LIHTC model. First, I tried to create new objects to capture the LIHTC information in the lab_05_source_tn.R file. Then I created new data sets with that. I imported d6 at the beginning of the RMD document.
<img width="659" alt="Screenshot 2021-11-20 152129" src="https://user-images.githubusercontent.com/69982382/142742469-0a965f50-2631-4fbb-bdb2-9912e0f6552a.png">

When I try to run the model with treat.lihtc, I get an error that the variable lengths differ. I don't really know what to make of that.
<img width="633" alt="Screenshot 2021-11-20 152309" src="https://user-images.githubusercontent.com/69982382/142742503-d1c4ebba-8ff6-4d13-8204-c3df185a98c4.png">

I tried just using "treat" in the model, wondering if the treat.lihtc was already in the dataset so just the general "treat" variable should be in the model. That did run a stargazer table when I'm just running the code. However, when I then try to knit it, it says it can't find the treat variable, which is odd to me because it used it in the nmtc model.

Here is running with just treat in the model
<img width="635" alt="Screenshot 2021-11-20 152556" src="https://user-images.githubusercontent.com/69982382/142742588-459c8a5a-dda8-4096-b991-43b706f1a22a.png">

Here is after knitting
<img width="656" alt="Screenshot 2021-11-20 152727" src="https://user-images.githubusercontent.com/69982382/142742595-1d6287dc-03b8-4926-936a-206036468d5e.png">

**Comment by tim-ness** [comment]
I think I figured this out from typing it all out.

**Comment by castower** [comment]
Glad you figured it out @tim-ness!
